### ISSUE TITLE
Specify the public IP address(es) of the connection

### ISSUE THREAD

**Issue by C-Duv** [pluginsGLPI/connections#10]
I think it would be useful if we could store in GLPI all the public IP addresses the ISP provides for a given connection.

It could then be used in other softwares (via the REST API): monitoring, list, ...

**Comment by andreasmalta** [comment]
I agree 100% to have a field for IP address, and also username and password please. I would like to document our pppoe settings of all our connections but there is no obvious place where to save this information currently.

**Comment by tsmr** [comment]
For User / Passwor - we had link with accounts plugin

**Comment by C-Duv** [comment]
How do I programmatically know which of the linked network device and which interface of this network device is publicly facing Internet?
