### ISSUE TITLE
Liaison avec Comptes, Ordinateurs et Certificats

### ISSUE THREAD

**Issue by redfish0** [pluginsGLPI/connections#13]
Bonjour,
Je cherche à documenter mes VPNs, ceux-ci étant parfois terminés sur un ordinateur (et non pas un équipement réseau) et utilisant des méthode d'authentification multiples j'aurai aimé pouvoir lier les "Connexions" avec des ordinateurs, des comptes (plugin account) et des certificats.

Est-ce envisageable ?

Merci.

Patrick

**Comment by tsmr** [comment]
Ok into next 9.5 version

**Comment by C-Duv** [comment]
Thanks!

**Comment by seblveb** [comment]
Hi everyone,

I'm looking for a solution to map and document the network architecture, including VPNs, firewalls, and network links between servers, cameras, and networks in GLPI.

Currently, GLPI provides excellent asset management and ticketing capabilities, but I need to visualize and document the following:

VPN connections between servers and cameras.

Network architecture, including physical links between switches, servers, and cameras.

Firewall rules and their relationship with the devices they protect.

Links between different network segments (e.g., LAN, WAN, VPN).

I have already looked into the Archires plugin, which generates network diagrams based on the assets in GLPI, but it doesn’t support VPN or firewall visualizations.

Is there a plugin or method within GLPI to:

Map VPN connections between devices?

Visualize firewall rules and how they relate to devices in the network?

Document network links and topologies, including both physical and virtual connections (VPN)?

Any advice or suggestions for plugins, tools, or workarounds would be highly appreciated!

Thank you!
