### ISSUE TITLE
Nothing happened

### ISSUE THREAD

**Issue by pva1967** [pluginsGLPI/connections#14]
Hi, 
We got Connections plugin in setup/plugin window and enabled it.
But nothing happened to Dropdowns - no new items or types nor asset types.
however  we see the tables in the database created by Connection plugin glpi_plugin_connections_configs, glpi_plugin_connections_connections etc.

What are we doing wrong?

GLPI 9.5.5 
FusionInventory 9.5+3.0

**Comment by tsmr** [comment]
Installed with marketplace or into /plugins folder ?

**Comment by pva1967** [comment]
> Installed with marketplace or into /plugins folder ?
haven't found it on marketplace - so downloaded the latest release to /plugins folder.

**Comment by armanduchi** [comment]
Having the same problem. I would appreciate any suggestions

**Comment by bacus99** [comment]
Try to download directly from GitHub.  The package available seems to not be compatible with 9.5.  The version on GitHub is, but not published

**Comment by armanduchi** [comment]
GLPI 9.5.5
Git clone and same problem. I can see connections tables in database, but no "option" under Assets or DropDowns

I can "force" navigation under X.X.X.X//plugins/connections/front/connection.php put nothin appears to add a new connection

Thanks in advance

**Comment by armanduchi** [comment]
OK
In setup.php file, if we delete the if sentence ---> I works

I am alway connected as "super-admin" user (testing)

      if (Session::haveRight("plugin_connections_connection", READ)) {
         $PLUGIN_HOOKS["menu_toadd"]['connections'] = ['assets' => 'PluginConnectionsMenu'];
      }

**Comment by armanduchi** [comment]
OK
Finally SOLVED
After enabling plugin ---> Edit profile and under "Connection Tab" Enable "Read, update, create, delete, ....."


Some updated documentation would be appreciated.

**Comment by bacus99** [comment]
:)  Nice!
