### ISSUE TITLE
GLPI vers 10 ?

### ISSUE THREAD

**Issue by bbreton09** [pluginsGLPI/connections#15]
Bonjour, la branche master n'est pas compatible avec la version stable de GLPI 9.5.6 ?

J'ai le message ci dessous a l'installation du plugin
Ce plugin requiert GLPI >= 10.0 et < 11.0
--

**Comment by bbreton09** [comment]
J'ai édité la ligne 109 du setup pour remplacer 10 par 9 et tout semble fonctionner normalement :)

**Comment by btry** [comment]
Bonjour

Vous vous exposez potentiellement à des incompatibilités et des bugs, en modifiant la vérification de version de cette manière. Vous avez probablement téléchargé le source du plugin depuis la branche master.

Si vous voulez le plugin pour une version 9.x prenez une release compatible. Il vous faut probablement celle ci : https://github.com/pluginsGLPI/connections/releases/tag/9.5

**Comment by bbreton09** [comment]
Merci c'est effectivement beaucoup mieux avec la bonne version.
