### ISSUE TITLE
Liaison avec les tickets non possible

### ISSUE THREAD

**Issue by flegastelois** [pluginsGLPI/connections#2]
![image008](https://cloud.githubusercontent.com/assets/470612/10366874/87716d36-6dcd-11e5-860b-e01a8fbe2e1d.png)

**Comment by neeftarah** [comment]
Afin de pouvoir lié des connections à des tickets, il faut :
- Ajouté les "Connections" dans les objets liable à des tickets
"Administration > Profil : Onglet Assistance".
- Que la connexion en elle-même puisse être lié à des tickets (Infos
globales de la connexion)

2015-10-08 15:02 GMT+02:00 François Legastelois <notifications@github.com>:

**Comment by flegastelois** [comment]
ok
