### ISSUE TITLE
Page principale d'une "connection" - non disponible

### ISSUE THREAD

**Issue by flegastelois** [pluginsGLPI/connections#4]
Une fois la connexion créée, on ne retrouve pas le formulaire principale.

![selection_042](https://cloud.githubusercontent.com/assets/470612/10395928/d4c7b680-6e9f-11e5-8786-1c97bcc14117.png)

**Comment by bacus99** [comment]
SQL Error

2015-10-13 09:21:54 [6@lidsnocprd01]
  *** MySQL query error:
  SQL: SELECT t.*, it.`id` AS items_id, `glpi_entities`.`ID` AS entity
                         FROM `glpi_plugin_connections_connections_items` it, `glpi_networkequipments` t
                         LEFT JOIN `glpi_entities` ON (`glpi_entities`.`id` = t.`entities_id`)
                         WHERE t.`id` = it.`items_id`
                         AND it.`itemtype` = \'NetworkEquipment\'
                         AND it.`plugin_connections_connections_id` = \'145\'
                          AND  ( `glpi_networkequipments`.`entities_id` IN (\'0\', \'202\', \'214\', \'246\', \'446\', \'211\', \'212\', \'434\', \'209\', \'210\', \'215\', \'216\', \'217\', \'219\', \'221\', \'222\', \'223\', \'224\', \'225\', \'227\', \'229\', \'231\', \'232\', \'233\', \'235\', \'236\', \'239\', \'240\', \'241\', \'242\', \'243\', \'244\', \'245\', \'299\', \'363\', \'366\', \'372\', \'405\', \'438\', \'453\', \'206\', \'391\', \'325\', \'329\', \'390\', \'442\', \'444\', \'441\', \'367\', \'374\', \'213\', \'248\', \'250\', \'203\', \'369\', \'443\', \'445\', \'447\', \'448\', \'449\', \'452\', \'450\', \'394\', \'435\', \'371\', \'456\', \'251\', \'252\', \'253\', \'254\', \'255\', \'256\', \'257\', \'258\', \'259\', \'260\', \'261\', \'262\', \'263\', \'269\', \'271\', \'273\', \'274\', \'275\', \'277\', \'278\', \'279\', \'440\', \'281\', \'282\', \'285\', \'286\', \'287\', \'289\', \'291\', \'292\', \'388\', \'294\', \'295\', \'296\', \'379\', \'351\', \'340\', \'336\', \'300\', \'301\', \'303\', \'377\', \'305\', \'308\', \'309\', \'311\', \'322\', \'324\', \'327\', \'328\', \'330\', \'332\', \'333\', \'334\', \'335\', \'355\', \'352\', \'350\', \'349\', \'347\', \'346\', \'345\', \'338\', \'354\', \'344\', \'343\', \'342\', \'341\', \'359\', \'360\', \'362\', \'409\', \'373\', \'375\', \'403\', \'408\', \'407\', \'412\', \'413\', \'414\', \'415\', \'416\', \'417\', \'420\', \'421\', \'422\', \'423\', \'424\', \'426\', \'428\', \'429\', \'430\', \'431\', \'432\', \'433\', \'436\', \'437\', \'457\', \'451\', \'454\', \'458\', \'459\', \'460\', \'378\', \'376\', \'370\', \'317\', \'318\', \'319\', \'320\', \'321\', \'323\', \'326\', \'455\')  ) 
                          AND t.`is_template` = \'0\'
                         ORDER BY `glpi_entities`.`completename`, t.`name`;
  Error: Unknown column 'glpi_networkequipments.entities_id' in 'where clause'
  Backtrace :
  ...s/connections/inc/connection_item.class.php:198 
  ...s/connections/inc/connection_item.class.php:582 PluginConnectionsConnection_Item->showItemFromPlugin()
  inc/commonglpi.class.php:455                       PluginConnectionsConnection_Item::displayTabContentForItem()
  ajax/common.tabs.php:87                            CommonGLPI::displayStandardTab()

**Comment by flegastelois** [comment]
fixed by c0ceeda0b93bae2e31508f8c53ab43c49e97a343
