### ISSUE TITLE
Nothing to add in dropdown

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/connections#5]
Hello

I have installed the plugin on glpi 0.90 last master branch, I have tried also on 0.85.2.

I am on super admin, in connection dropdown nothing is listed. I have tried to change entity but always nothing.

**Comment by flegastelois** [comment]
Hi,

Thank you for your tests.

What "connection dropdown" you talking about? 
In Ticket ? In NetworkEquipment ?

Regards,

**Comment by tsmr** [comment]
So old. I close
